// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAUOXWj6aQMVsOaOO7QRURZQRQw08xN2w',
    appId: '1:87834972004:web:d93c0cc14d511d3a6af471',
    messagingSenderId: '87834972004',
    projectId: 'phone-otp-signup',
    authDomain: 'phone-otp-signup.firebaseapp.com',
    storageBucket: 'phone-otp-signup.appspot.com',
    measurementId: 'G-CTVL27J11V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH_cemxGtLZa8fdiaN36k97abOLfW6TVs',
    appId: '1:87834972004:android:5e8b3649c3a34e456af471',
    messagingSenderId: '87834972004',
    projectId: 'phone-otp-signup',
    storageBucket: 'phone-otp-signup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsXy4Torq0Z7KhKYZPZYsso-4o_SAFcls',
    appId: '1:87834972004:ios:093f89709f6545646af471',
    messagingSenderId: '87834972004',
    projectId: 'phone-otp-signup',
    storageBucket: 'phone-otp-signup.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsXy4Torq0Z7KhKYZPZYsso-4o_SAFcls',
    appId: '1:87834972004:ios:7fbf29fc3410faa76af471',
    messagingSenderId: '87834972004',
    projectId: 'phone-otp-signup',
    storageBucket: 'phone-otp-signup.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
